name: Deploy Vite site to GitHub Pages (subfolder)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Folder that contains your package.json
  APP_DIR: tagmax-onboard-buddy-main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache removed to avoid lockfile warnings when no lockfile is present
          # cache: 'npm'

      - name: Install dependencies
        working-directory: ${{ env.APP_DIR }}
        run: npm install

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.APP_DIR }}/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
